version: '3.8'

services:
  postgresdb:
    container_name: "postgresdb"
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: demo-app